# Generated by Django 5.1.2 on 2024-10-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic.jpg', upload_to='profile_pictures'),
        ),
    ]
